#!/bin/sh

test -f /etc/astra/config.lua || exit 0
test -f /etc/astra/astra.conf || exit 0

case "$1" in
  start)
    echo "Starting astra with config.lua as config file"
    ulimit -n 65536
    /usr/bin/astra --pid /var/run/astra.pid /etc/astra/config.lua &
    ;;
  start-normal)
    echo "Starting astra with astra.conf as config file"
    ulimit -n 65536
    /usr/bin/astra --pid /var/run/astra.pid /etc/astra/astra.conf &
    ;;
  stop)
    echo "Stopping astra"
    kill `cat /var/run/astra.pid`
    ;;
  restart|reload|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload|start-normal}"
    exit 1
esac

exit 0
